Cockple/Cockple_FE

src/App.tsx, src/components/common/system/header/MainHeader.tsx, src/components/common/system/header/PageHeader.tsx, src/components/common/system/navbar/NavItem.tsx, src/components/common/system/navbar/Navbar.tsx
-   [ ] 버그 수정
-   [x] CSS 등 사용자 UI 디자인 변경
-   [ ] 문서 수정
resolves #14 
- 전체 레이아웃 양쪽에 16px씩 패딩값 추가했습니다!
- navbar의 찜 라우팅이 잘못되어있어서 수정했습니다
- 피그마에서 전체 다 양쪽에 16px씩 있어서 그거 반영해놨으니까 참고해서 개발해주시면 될 것 같습니다!
=> [FIX] 라우팅 오류 수정 & 레이아웃 수정

src/components/common/Btn_Static/Btn_Static.tsx, src/components/common/Btn_Static/Text/Grad_GR400_L.tsx, src/components/common/Btn_Static/Text/Grad_Mix_L.tsx
Btn_Staic.tsx 수정
-   [ ] 버그 수정
-   [x] 코드 리팩토링
-   [ ] 문서 수정
[disabledToDefault.webm](https://github.com/user-attachments/assets/87020808-cffc-43ae-9144-b484f8ee9464)
위 영상은 처음에는 disabled 였다가 3초 후 자동으로 default로 변경되는 로직을 구현한 것입니다!
코드는 아래 첨부 이미지와 같습니당!
=> [FEAT] disabled->default 같은 상태 변경 가능하도록 리팩토링

src/components/chat/ChatList.tsx, src/components/common/TabSelector.tsx
-   [ ] 버그 수정
-   [x] 코드 리팩토링
-   [ ] 문서 수정
resolves #22 
채팅 컴포넌트인 ChatList와
공용 컴포넌트인 TabSelector를 수정했습니다.
**TabSelector는 아래 첨부한 이미지 부분입니다. 채팅페이지, 찜 페이지에 사용되어 components/common/ 에 만들었습니다!**
=> [FEAT] ChatList(채팅 컴포넌트), TabSelector(TabBtn 이용한 컴포넌트) 수정

src/App.tsx, src/components/common/Btn_Static/Text/Grad_Mix_L.tsx, src/components/common/DynamicBtn/FilterBtn.tsx, src/components/common/Sort.tsx, src/components/group/main/CautionModal.tsx, src/components/home/mock/homeMock.ts, src/pages/group/GroupPage.tsx, src/pages/group/GroupRecommendFilterPage.tsx, src/pages/group/GroupRecommendPage.tsx, src/pages/home/CautionModal.tsx, src/pages/home/ExerciseFilterPage.tsx, src/pages/home/Recommendpage.tsx, src/store/useExerciseFilterStore.ts, src/store/useGroupRecommendFilterStore.ts
-   [ ] 버그 수정
-   [ ] 문서 수정
resolves #55
- 모임페이지랑 모임 추천 페이지 만들었습니다
<br />
<br />
<br />
- 필터에 값이 있을때만 필터버튼이 clicked상태가 되어야 해서 외부에서 클릭 상태를 관리할 수 있도록 수정했습니다. forceState값을 FilterBtn.tsx에서 옵셔널 프로퍼티로 설정해서 props로 받도록 했습니다 혹시 문제있으면 말씀해주세요!
<br />
=> [FEAT] 모임 페이지 & 모임추천 페이지 ui 구현

index.html, package-lock.json, package.json, src/assets/icons/map_mylocation.svg, src/components/group/main/TextBox_M.tsx, src/pages/group/GroupPage.tsx, src/pages/group/GroupRecommendFilterPage.tsx, src/pages/home/ExerciseFilterPage.tsx, src/pages/home/ExerciseMapPage.tsx
-   [ ] 버그 수정
-   [ ] 문서 수정
resolves #
- 카카오 디벨로퍼에서 지도 api를 사용하려면 서비스 화면이 배포가 되어야 승인이 나서 일단 제가 예전에 혼자 사용하던 애플리케이션 키를 사용해서 지도 연결시켜놨습니다..배포까지 되고 나서 추후에 승인나면 그걸로 수정해볼게요..!
- 위치 정하는 뷰도 얼릉 하겠습니다..!
- 카카오 지도가 되려면 키가 있어야해서 단톡에 보내놓을게요! .env파일에 넣어주시면 됩니다
https://github.com/user-attachments/assets/2c6ffef0-06b5-4f31-9fd5-ef7421666f07
- framer-motion 설치해서 npm install 한 번 부탁드립니다!
=> [FEAT] 지도로 운동 찾기 (카카오 맵) ui

vite.config.ts
=> fix: storybook 오류 해결

src/pages/mypage/MyPageExerciseDetailPage.tsx
=> fix: Caution Icon 경로 오류 수정

src/components/common/contentcard/LocationList.tsx
=> fix: LocationList 아이콘 이름 오류 수정

src/pages/group/MyGroupDetail/ExerciseDetail.tsx, src/pages/group/MyGroupDetail/MyExerciseDetail.tsx
=> fix: Caution.svg 경로 수정

src/components/common/Date_Time/DayNum.tsx, src/components/common/Date_Time/MonthCalendar.tsx, src/components/common/Drop_Box/DropCheckBox.tsx, src/components/common/DynamicBtn/ChatBtn.tsx, src/components/common/DynamicBtn/CheckBoxBtn.tsx, src/components/common/DynamicBtn/FilterBtn.tsx, src/components/common/DynamicBtn/TagBtn.tsx, src/components/common/LocationField.tsx, src/components/common/Search_Filed/InputField.tsx, src/components/common/Search_Filed/InputSlider.tsx, src/components/common/Search_Filed/SearchFieldBtn.tsx, src/components/group/groupMaking/SingleImgUploadBtn.tsx, src/components/login/LoginSwiping.tsx, src/components/login/SplashScreen.tsx, src/pages/alarm/AlertPage.tsx, src/pages/group/InviteGuest.tsx, src/pages/group/groupMaking/GroupActivity.tsx, src/pages/group/groupMaking/GroupBasicInfo.tsx, src/pages/home/CautionModal.tsx, src/pages/home/EditLocationPage.tsx, src/pages/location/LocationMapPage.tsx, src/pages/login/LoginPage.tsx, src/pages/mypage/MyPageEditPage.tsx, src/pages/mypage/MyPageMedalAddpage.tsx, src/pages/onboarding/OnBoardingConfirmStartPage.tsx, src/pages/onboarding/OnboardingConfirmPage.tsx, src/pages/onboarding/OnboardingInfoPage.tsx, src/pages/onboarding/OnboardingPage.tsx, src/pages/onboarding/OnboardingProfilePage.tsx
- 배포시 이미지 깨지는 오류 해결을 위해 이미지 경로 뒤에 ?url 추가
=> fix: 이미지 경로 ?url 추가

src/components/like/CautionExerciseModal.tsx, src/components/like/CautionGroupModal.tsx
-   [ ] 버그 수정
-   [ ] 문서 수정
resolves #
=> [FEAT] 찜 경고 모달창

src/components/common/contentcard/Member.tsx, src/components/group/groupMaking/GroupMember.tsx, src/components/group/groupMaking/MemberInfo.tsx, src/pages/group/InviteGuest.tsx
-   [x] 버그 수정
-   [ ] 문서 수정
resolves #122
=> [FIX] type 오류 해결

src/api/chat/rawWs.ts, src/components/chat/ChatDetailTemplate.tsx, src/components/chat/ChatList.tsx, src/components/chat/GroupChatDetailTemplate.tsx, src/components/common/chat/BottomChatInput.tsx, src/components/common/contentcard/Member.tsx, src/hooks/useRawWsConnect.ts, src/pages/group/MemberRequest.tsx, src/types/memberJoinRequest.ts, src/utils/time.ts
-   [x] 버그 수정
-   [ ] 문서 수정
resolves #
=> [FEAT] npm run build 후 에러 수정

src/api/Exercise/participants.ts, src/components/common/contentcard/Member.tsx
-   [ ] 버그 수정
-   [ ] 문서 수정
resolves #
=> [BUG] 배포 오류 수정 

src/components/common/LoadingSpinner.tsx, src/components/common/LocationField.tsx, src/components/common/system/navbar/Navbar.tsx, src/components/home/CautionModalLocation.tsx, src/components/home/MyGroupWorkoutSection.tsx, src/components/home/RecommendedWorkoutSection.tsx, src/layout/PrivateRoute.tsx, src/pages/home/EditLocationPage.tsx, src/pages/home/Recommendpage.tsx
-   [ ] 버그 수정
-   [ ] 문서 수정
#149 
- 위치 수정 모달창
- 로딩 스피너 구현
=> feat: 로딩 스피너 구현 & 위치 수정 모달

src/components/common/DynamicBtn/ChatBtn.tsx, src/components/common/DynamicBtn/CheckBoxBtn.tsx, src/components/common/DynamicBtn/DropDownBtn.tsx, src/components/common/DynamicBtn/DynamicBtn.tsx, src/components/common/DynamicBtn/FilterBtn.tsx, src/components/common/DynamicBtn/TabBtn.tsx, src/pages/home/MyGroupExercisePage.tsx
-   [ ] 버그 수정
-   [ ] 문서 수정
resolves #
=> fix: 경로 오류 수정

src/components/login/SplashScreen.tsx, src/layout/PrivateRoute.tsx, src/store/useSplashStore.ts
-   [ ] 버그 수정
-   [ ] 문서 수정
resolves #
=> fix: 배포환경 모바일 스플래쉬 안없지는 문제

src/store/useSplashStore.ts
-   [ ] 버그 수정
-   [ ] 문서 수정
resolves #
=> fix: 스플래쉬 localstorage -> sessionStorage로 변경

src/App.tsx, src/pages/location/LocationMapPage.tsx, src/pages/location/LocationSearchPage.tsx
-   [ ] 버그 수정
-   [ ] 문서 수정
resolves #
=> fix: 오류 수정

src/api/chat/chatList.ts, src/api/chat/getRoomIdByPartyId.ts, src/components/chat/GroupChatDetailTemplate.tsx, src/pages/alarm/AlertPage.tsx, src/pages/group/GroupChatPage.tsx
-   [x] 버그 수정
-   [ ] 문서 수정
resolves #
https://github.com/user-attachments/assets/fa01e9fc-951b-4c5c-a69d-26d751036d87
=> [FEAT] 모임-> 채팅 오류 해결

src/components/chat/ChatDetailTemplate.tsx, src/components/chat/GroupChatDetailTemplate.tsx, src/pages/group/GroupChatPage.tsx
-   [x] 버그 수정
-   [ ] 문서 수정
resolves #
=> [FEAT] 채팅방 오류 수정

src/App.tsx, src/api/chat/rawWs.ts, src/components/chat/GroupChatDetailTemplate.tsx, src/hooks/useRawWsConnect.ts, src/pages/group/GroupChatPage.tsx
-   [ ] 버그 수정
-   [ ] 문서 수정
resolves #
=> [FEAT] accessToken 없으며 웹소켓 연결 시도 안 함

src/api/api.ts, src/layout/PrivateRoute.tsx, src/store/useSplashStore.ts
-   [ ] 버그 수정
-   [ ] 문서 수정
resolves #
=> fix: 스플래쉬 오류 수정

src/App.tsx, src/api/chat/rawWs.ts, src/components/chat/ChatDetailTemplate.tsx, src/hooks/useRawWsConnect.ts, src/pages/chat/ChatPage.tsx, src/store/useChatWsStore.ts, src/utils/auth.ts
-   [x] 버그 수정
-   [ ] 문서 수정
resolves #
=> [FEAT] 배포 후 웹소켓 연결 거절당함-> memberId 다름 수정

src/components/chat/ChatDetailTemplate.tsx, src/components/chat/GroupChatDetailTemplate.tsx, src/utils/auth.ts
-   [x] 버그 수정
-   [ ] 문서 수정
resolves #
=> [FIX] 채팅에서 닉네임 호출 수정

src/layout/GroupLayout.tsx
-   [ ] 버그 수정
-   [ ] 문서 수정
resolves #
=> feat: 모입 가입하기 오류 메시지

src/api/chat/rawWs.ts, src/components/chat/ChatDetailTemplate.tsx, src/hooks/useRawWsConnect.ts, src/pages/chat/ChatPage.tsx, src/store/useChatWsStore.ts, src/types/chat.ts
-   [ ] 버그 수정
-   [ ] 문서 수정
resolves #
=> [FIX] 채팅 필드 교체

src/layout/GroupLayout.tsx
-   [x] 버그 수정
-   [ ] 문서 수정
resolves #
=> fix: 새로고침시 그룹명 날라가는 오류 수정

src/pages/group/GroupHomePage.tsx
-   [ ] 버그 수정
-   [x] CSS 등 사용자 UI 디자인 변경
-   [ ] 문서 수정
resolves #
=> feat: 운동 시작되면 버튼 사라지도록 수정

src/components/like/LikedList.tsx, src/pages/alarm/AlertPage.tsx, src/types/liked.ts, src/utils/gradeMapper.ts
-   [ ] 버그 수정
-   [ ] 문서 수정
resolves #
=> [FIX] 알림 api 연동 및 찜 한글 급수로 수정

src/pages/home/EditLocationPage.tsx
-   [x] 버그 수정
-   [ ] 문서 수정
resolves #
=> fix: 수정 완료 버튼 누르면 홈으로 이동하도록 수정

src/api/contest/contestmy.ts, src/components/group/InputField.tsx, src/pages/group/AdminMenu/EditGroupInfoDefault.tsx, src/pages/group/MyGroupDetail/MemberDefault.tsx, src/pages/group/MyGroupDetail/MyExerciseDetail.tsx, src/pages/mypage/MyPageEditPage.tsx, src/pages/mypage/MyPageMedalDetailPage.tsx
-   [ ] 버그 수정
-   [ ] 문서 수정
resolves #
=> 로딩 스피너 및 오류 수정

src/pages/location/LocationMapPage.tsx
-   [x] 버그 수정
-   [ ] 문서 수정
resolves #
=> feat: 지도 뒤로가기 오류 수정

src/components/common/Btn_Static/Text/White_L_Test.tsx, src/pages/group/GroupPage.tsx, src/pages/mypage/MyPage.tsx
-   [ ] 버그 수정
-   [x] CSS 등 사용자 UI 디자인 변경
-   [ ] 문서 수정
resolves #
=> style: 내 모임 정렬

vite.config.ts
-   [ ] 버그 수정
-   [x] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
-   [ ] 문서 수정
resolves #
=> chore(pwa): 앱 이름 및 메타데이터 수정

dev-dist/sw.js, src/components/common/Date_Time/DateAndPicker.tsx
-   [ ] 버그 수정
-   [ ] 문서 수정
resolves #
=> [FEAT]스크롤 달력 수정

src/components/common/chat/ChattingComponent.tsx, src/pages/group/MemberRequest.tsx
-   [ ] 버그 수정
-   [ ] 문서 수정
resolves #
=> [bug] 멤버 신청 관리 프로필 없을 때

dev-dist/sw.js, src/components/common/contentcard/Member.tsx, src/components/group/InviteGuestList.tsx, src/pages/group/InviteGuest.tsx, src/types/guest.ts
-   [ ] 버그 수정
-   [ ] 문서 수정
resolves #
=> [FEAT] 게스트 초대하기 number수정

src/components/group/InviteGuestList.tsx, src/pages/group/InviteGuest.tsx
-   [ ] 버그 수정
-   [ ] 문서 수정
resolves #
=> fix: 경로 오류

src/App.tsx, src/pages/group/MyGroupDetail/MemberDefault.tsx, src/pages/group/MyGroupDetail/MyExerciseDetail.tsx, src/pages/mypage/MyPageProfile.tsx
-   [ ] 버그 수정
-   [ ] 문서 수정
resolves #336
=> [FIX] 경로 수정

src/App.tsx, src/api/member/profile.ts, src/pages/mypage/MyPageMyGroupPage.tsx, src/pages/mypage/MyPageProfile.tsx
-   [ ] 버그 수정
-   [ ] 문서 수정
resolves #339
=> [FEAT] 다른 유저 모임 조회 API 연결 완료 

src/App.tsx
-   [ ] 버그 수정
-   [ ] 문서 수정
resolves #349
=> bug : 배포 오류

src/components/group/InviteGuestList.tsx, src/pages/group/InviteGuest.tsx
-   [x] 버그 수정
-   [ ] 문서 수정
resolves #355
=> [FEAT]게스트 초대하기 수정

src/hooks/useRawWsConnect.ts, src/index.css, src/pages/group/GroupCalendarPage.tsx, src/pages/location/LocationSearchPage.tsx
-   [ ] 버그 수정
-   [x] CSS 등 사용자 UI 디자인 변경
-   [ ] 문서 수정
resolves #357 
- 운동 공유하기 기능 추가
=> feat: 운동 공유하기 기능 추가
